### ISSUE TITLE
Error in the android manifest [Godot 3.2.3 rc2]

### ISSUE THREAD

**Issue by lentsius-bark** [GameAnalytics/GA-SDK-GODOT#1]
### Error when trying to build for android
```
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:30:68-95
  	is also present at [com.gameanalytics.sdk:gameanalytics-android:5.2.4] AndroidManifest.xml:14:18-44 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:30:5-68:19 to override.

```

I should add I'm using this in conjunction with AdMob from Shinnil.

### Solution
add:
```
tools:replace="android:allowBackup"
```
to the `<application>` element but I'm not sure whether that's the desired solution and if so, it might be worth adding to documentation.

Also, I'm excited about the official plugin from GA, it's absolutely fantastic.

**Comment by the1schwartz** [comment]
Ok thanks for reporting this. I have updated the GA native android lib used by the plugin and I have removed the android:allowBackup value inside the manifest file their since the value by default is set to true anyway so now there shouldn't be any conflicts when building for Android after updating to the latest version of the plugin (v1.0.1)

**Comment by lentsius-bark** [comment]
Fantastic, thanks!
